# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3360:3360
    volumes:
      - ../data/:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
